name: Build and Release

on:
  push:
    tags:
      - 'v*' # 当推送 v 开头的标签时触发（例如 v1.0.0）

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn' # 使用 Yarn 专用缓存

      - name: Install dependencies
        run: yarn install --frozen-lockfile # Yarn 的确定性安装

      - name: Build project
        run: yarn build

      - name: Create release assets
        run: |
          cd dist
          zip -r ../release-dist-${GITHUB_REF#refs/tags/}.zip ./*

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${GITHUB_REF#refs/tags/}
          tag_name: ${GITHUB_REF#refs/tags/}
          files: |
            release-dist-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
